server:
  port: 9977

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.godmk.tool.easyreport.dao

# db config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    #spring.datasource.url=jdbc:mysql://mysqldb:3306/myblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    url: jdbc:mysql://192.168.31.98:3306/myblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: mysql123
    initialSize: 20
    minIdle: 10
    maxActive: 100

  profiles:
    active: jdbc
  redis:
    # Redis服务器地址
    host: 192.168.31.98
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: '123456'
    # Redis数据库索引（默认为0）
    database: 6
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 6000

# thymeleaf
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.check-template-location: true
spring.thymeleaf.suffix: .html
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.content-type: text/html
spring.thymeleaf.mode: HTML5
spring.thymeleaf.cache: false


